version: '3.8'

services:
  information-board:
    build: .
    container_name: information-board
    restart: unless-stopped
    ports:
      - "3030:3000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=/app/data/board.db
      - NEXT_PUBLIC_BASE_URL=http://localhost:3030
    networks:
      - services

networks:
  services:
    external: true
